"use strict";
module.exports = {
    config: {
        updateChannel: 'stable',
        fontSize: 18,
        fontFamily: '"Iosevka Term", Menlo, "DejaVu Sans Mono", Consolas, "Lucida Console", monospace',
        fontWeight: 'normal',
        fontWeightBold: 'bold',
        lineHeight: 1,
        letterSpacing: 0,
        cursorColor: '#e07d13',
        cursorAccentColor: '#000',
        cursorShape: 'BLOCK',
        cursorBlink: false,
        foregroundColor: '#cccccc',
        backgroundColor: '#191323',
        selectionColor: '#220525',
        borderColor: '#333',
        css: '',
        termCSS: '',
        workingDirectory: '',
        showHamburgerMenu: '',
        showWindowControls: '',
        colors: {
            black: '#17141f',
            red: '#ff6b7f',
            green: '#00bd9c',
            yellow: '#e6c62f',
            blue: '#22e8df',
            magenta: '#dc396a',
            cyan: '#56b6c2',
            white: '#f1f1f1',
            lightBlack: '#495162',
            lightRed: '#fe9ea1',
            lightGreen: '#98c379',
            lightYellow: '#f9e46b',
            lightBlue: '#91fff4',
            lightMagenta: '#da70d6',
            lightCyan: '#bcf3ff',
            lightWhite: '#ffffff',
            limeGreen: '##98d33f',
            lightCoral: '#fe5ee1',
        },
        shell: '',
        shellArgs: ['--login'],
        env: {},
        bell: 'SOUND',
        copyOnSelect: false,
        defaultSSHApp: true,
        quickEdit: false,
        macOptionSelectionMode: 'vertical',
        webGLRenderer: true,
        webLinksActivationKey: '',
        disableLigatures: true,
        disableAutoUpdates: false,
        screenReaderMode: false,
        preserveCWD: true,
    },
    plugins: [],
    localPlugins: [],
    keymaps: {
    },
}
