# ~/.config/starship.toml
add_newline = true

command_timeout = 1000

format = """$env_var $all"""

# Change the default prompt characters
[character]
success_symbol = "[  ](#00bd9c)"
error_symbol = "[  ](#ff6b7f)"

# Shows an icon that should be included by zshrc script based on the distribution or os
[env_var.STARSHIP_DISTRO]
format = '[$env_value](white)'
variable = "STARSHIP_DISTRO"
disabled = false

# Shows the username
[username]
style_user = "#bcf3ff"
style_root = "white"
format = "[$user]($style) "
disabled = false
show_always = true

[hostname]
ssh_only = false
format = "on [$hostname](#495162) "
disabled = false

[directory]
truncation_length = 2
truncation_symbol = "…/"
home_symbol = " ~"
style = "#f9e46b"
read_only_style = "#dc396a"
read_only = "  "
format = "at [$path]($style)[$read_only]($read_only_style) "

[git_branch]
symbol = "  "
format = " via [$symbol$branch]($style) "
truncation_symbol = "…/"
style = "bold #00bd9c"

[git_status]
format = '[\($all_status$ahead_behind \)]($style)'
style = "bold #00bd9c"
conflicted = "  "
up_to_date = "  "
untracked = "  "
ahead = " ⇡${count} "
diverged = " ⇕⇡${ahead_count} ⇣${behind_count} "
behind = " ⇣${count} "
stashed = "  "
modified = "  "
staged = ' [++\($count\)](#00bd9c) '
renamed = " 襁 "
deleted = "  "

[docker_context]
format = "via [ $context](bold #22e8df) "
disabled = false

[python]
symbol = "  "
style = "#e6c62f"
python_binary = "python3"
disabled = false

[nodejs]
format = "via [  $version](bold #98d33f) "
disabled = false

[ruby]
format = "via [ $version](#dc396a) "
disabled = false

[aws]
disabled = true

[package]
format = " is on [   $version ](#bcf3ff)"
